### ISSUE TITLE
Types are rather difficult to find.

### ISSUE THREAD

**Issue by duesee** [duesee/imap-codec#194]
The idea of having a `command`, `response`, and `message` module sounds nice in theory but makes the types unintuitive to find. Do we have a better idea?

* [x] #234

**Comment by epilys** [comment]
What about:
https://doc.rust-lang.org/rustdoc/advanced-features.html#add-aliases-for-an-item-in-documentation-search

**Comment by duesee** [comment]
Seems very useful. Thanks for the hint!

**Comment by duesee** [comment]
I think the new (old :P) module layout is already an improvement.

@epilys: IMAP calls the things in "FETCH" "message data item" and the things in "STATUS" "status data item".

In imap-codec, I called them `FetchAttribute` and `StatusAttribute`. Now, I could try to make these types easier to find by using "{message,status} data item" aliases OR rename them to `MessageDataItem` and `StatusDataItem`. Or even something different? What do you think?

**Comment by duesee** [comment]
I think I want to rename ...

* `FetchAttribute` -> `MessageDataItemName`
* `FetchAttributeValue` -> `MessageDataItem`
* `StatusAttribute` -> `StatusDataItemName`
* `StatusAttributeValue` -> `StatusDataItem`
