### ISSUE TITLE
Decoder::decode_static does not return 'static error

### ISSUE THREAD

**Issue by jakoschiko** [duesee/imap-codec#355]
This is the current signature of Decoder::decode_static:

```rust
fn decode_static<'a>(
    &self,
    input: &'a [u8],
) -> Result<(&'a [u8], Self::Message<'static>), Self::Error<'a>>
where
    Self::Message<'a>: IntoBoundedStatic<Static = Self::Message<'static>>
```

IMO it makes more sense to return `Self::Error<'static>` here because I think the default use case of this method is "I don't care about allocation, just gimme 'static". This would require to add the bound `Self::Error<'a>: IntoBoundedStatic<Static = Self::Error<'static>>`. This should be possible because as far as I know all actual error types derive `ToStatic`.

Alternatives:
- The caller could convert the error to `'static` at caller side
- We could provide another method `decode_static_static`
- Remove `decode_static` and force the user to always convert both message and error to `'static` themselves

**Comment by duesee** [comment]
Good catch! Yeah, I think it should be `Error<'static>`. Arguably, our error could also be owned. In the end, it's only the `tag` that introduces the lifetime?
