### ISSUE TITLE
feat: Python bindings.

### ISSUE THREAD

**Issue by duesee** [duesee/imap-codec#359]

**Comment by duesee** [comment]
Hey Henning! I'd like to assign you this issue. The way this works in GiHub is that you need to write some comment here -- content is irrelevant. Then, GitHub allows me to assign this issue to you.

So... What's up? :-)

**Comment by HenningHolmDE** [comment]
Sure, go ahead.

**Comment by HenningHolmDE** [comment]
@duesee What do you think about splitting/renaming this issue to more actionable issues for better representing the progress towards the milestone?

**Comment by duesee** [comment]
> @duesee What do you think about splitting/renaming this issue to more actionable issues for better representing the progress towards the milestone?

I would be very much in favor of it. This was kind of an "reminder" only but having more structure would be awesome.

**Comment by HenningHolmDE** [comment]
Now that #517 has landed and Python bindings are somewhat on their way, we can probably close this generic issue and track everything else separately. What do you think?
