### ISSUE TITLE
Check in CI that benchmarks, examples, and fuzz-targets compile

### ISSUE THREAD

**Issue by duesee** [duesee/imap-codec#36]
* [x] blocked by #38
* [x] compile benchmarks 15900ea5024d39375126a500c8174236227c05bc
* [x] compile examples 15900ea5024d39375126a500c8174236227c05bc
* [x] compile fuzz-targets #44

**Comment by franziskuskiefer** [comment]
I'd also suggest writing benchmarks that don't require nightly, either manually or with criterion or something else.

**Comment by duesee** [comment]
Thanks, I will check it out! But before that I would want to try https://github.com/nektos/act. The feedback loop of GH Actions is a bit limiting. Maybe you have a good strategy here, too? :-)

**Comment by franziskuskiefer** [comment]
I'm afraid `act` is the best there is right now.
