### ISSUE TITLE
Implement `Clone` for codec types

### ISSUE THREAD

**Issue by jakoschiko** [duesee/imap-codec#438]
I would like to have a `Clone` implementation for types like `CommandCodec`, etc. Any objects?

**Comment by duesee** [comment]
No objections.

**Comment by jakoschiko** [comment]
How do you handle backwards compatible changes like this one with regard to your v2 branch? 

- Merge to main and then rebase v2?
- Merge to both main and v2?
- Merge only to v2?

**Comment by duesee** [comment]
Let's ignore `v2` completely. I'll ask Quentin if he still needs it. If not, let's delete the `v2` branch quickly. So: Everything on main.

**Comment by duesee** [comment]
Quentin doesn't need it anymore. Let's delete it so it doesn't confuse us.
