### ISSUE TITLE
tests: Don't arbitrarily generate too deeply nested threads

### ISSUE THREAD

**Issue by duesee** [duesee/imap-codec#452]
Our `Arbitrary` implementations for recursive types are... meh... `Thread` derives `Arbitrary`, makes everything slower, and needs to be bounded (as `SearchKey`). This is all a pain point currently.

**Comment by jakoschiko** [comment]
See https://github.com/rust-fuzz/arbitrary/issues/78

**Comment by duesee** [comment]
I cheated and build the tree in reverse now (taking a few shortcuts) -- see #454. It seems to generate good enough test data. This unblocks fuzzing for now.

**Comment by duesee** [comment]
Idea: Can we use the async machinery to desugar recursive functions into state machines in order to "automatically" transform recursive functions to stack-based ones?

**Comment by jakoschiko** [comment]
> Idea: Can we use some async machinery to desugar recursive functions into state machines to "automatically" transform them into stack-based iterative functions?

I think this is sometimes called [trampoline](https://en.m.wikipedia.org/wiki/Trampoline_(computing)#High-level_programming). It's worth a try, but the biggest problem is probably the borrow checker.
