### ISSUE TITLE
docs: Delete outdated note about constant-time comparisons in `Secret`

### ISSUE THREAD

**Issue by jakoschiko** [duesee/imap-codec#461]
https://github.com/duesee/imap-codec/blob/eb4d6d188e56b7cb89fda833e364297a20dbb04d/imap-types/src/secret.rs#L19-L21

1. I don't understand the comment. Can you explain it to me/rephrase it?
2. Is `#[allow(clippy::derived_hash_with_manual_eq)]` still necessary? Currently `PartialEq` and `Eq` are derived. Same for the `Eq` related tests.

**Comment by duesee** [comment]
Neither the comment (nor `#[allow`) allow make sense anymore.
