### ISSUE TITLE
Use a more sustainable strategy of implementing `into_owned()`.

### ISSUE THREAD

**Issue by duesee** [duesee/imap-codec#50]

**Comment by jakoschiko** [comment]
PR for non-zero integers: https://github.com/fujiapple852/bounded-static/pull/43

**Comment by duesee** [comment]
Thank you very much @jakoschiko! As your PR (https://github.com/fujiapple852/bounded-static/pull/43) was already merged, we could either use the git version in imap-codec (with a rev key) for now or kindly ask FujiApple to release a new version on crates.io.

**Comment by duesee** [comment]
Thanks, @fujiapple852 👍🏻
