### ISSUE TITLE
Minimum supported Python version

### ISSUE THREAD

**Issue by HenningHolmDE** [duesee/imap-codec#545]
For the Python bindings, we have to decide on how to integrate with the Python release cycle, i.e. what will be the lowest Python version that the bindings will support.

The Python Developer's Guide has [a nice overview](https://devguide.python.org/versions/#versions) over the release cycle:
![Python release cycle](https://github.com/user-attachments/assets/0718d157-e1cf-4fa1-8e6c-60522d552828)

Currently, Python 3.8 is the oldest "supported" version (up until 2024-10) and the PyO3 template also sets `requires-python = ">=3.8"` in `pyproject.toml` by default.

Impact: The lowest supported Python version should be checked against in CI and newer Python language features cannot be used freely.

**Comment by duesee** [comment]
I don't have too much knowledge in this area but I feel that our priority should be to aim for low maintenance. Also, if there are features we want -- I somehow had structural pattern matching in mind which is usable from 3.10 -- we should give us this freedom. Not really an answer but hopefully a direction :-)

**Comment by HenningHolmDE** [comment]
As the "features we want" would only be used in examples, I would argue that forcing users to upgrade to a newer Python version should generally be avoided, as other packages might not yet (or no longer) be available for that version.
That said, it does of course not make sense for us to jump through too many hoops to support all "bugfix" versions.

**Comment by HenningHolmDE** [comment]
As it turned out, was building and testing all supported Python versions already part of the CI template provided by maturin which was adopted in #576.

For now, there is no strong reason for increasing the minimum supported Python over 3.8.
