### ISSUE TITLE
feat: Controlling quirks/extensions during runtime

### ISSUE THREAD

**Issue by HenningHolmDE** [duesee/imap-codec#547]
Currently, enabling/disabling of IMAP extensions and interoperability quirks is done though feature switches.

However it might helpful to be able to control these during runtime instead of during compile time.

This would also be helpful for the Python bindings, as "compile time" would mean distributing different extension binaries.

**Comment by duesee** [comment]
I generally think it's not worth it. The quirks are feature-gated, but, actually, we should make them enabled by default. The feature-gate might still be useful to detect non-compliant software, though. In other words: imap-codec should enable all quirks by default and the bindings don't need to be configurable IMO. Does this make sense?

**Comment by duesee** [comment]
Regarding extensions: IMAP extensions are rather difficult to turn on and off at runtime. I tried in some early implementations and don't want to go this route again :-/ Currently, we feature-gate new IMAP extensions and exclude them from SemVer compatibility. The idea is to include extensions on a major release basis. Actually... now would be a good time to reevaluate if we like some of the current feature-gated extensions. This is why I'm a bit torn about this default feature story.

**Comment by duesee** [comment]
@HenningHolmDE If you agree, I think we can close this issue? :-)

**Comment by HenningHolmDE** [comment]
> IMAP extensions are rather difficult to turn on and off at runtime. I tried in some early implementations and don't want to go this route again :-/

That‘s unfortunate. I would have hoped there is a better way to "configure" the codecs that through crate features. But if you‘ve already tried and it did not work out, sure, let‘s close this.

**Comment by duesee** [comment]
Yeah... I can tell a bit more about it the next time we meet.
