### ISSUE TITLE
feat: `Serialize`/`Deserialize` (serde) for types in `imap-codec`

### ISSUE THREAD

**Issue by HenningHolmDE** [duesee/imap-codec#555]
Currently, types in `imap-codec` do not implement `Serialize`/`Deserialize`. As reuired for the Python bindings, these are now implemented for `Fragment`.

However, this requirement will probably be dropped in one of the next development iterations for the bindings. Thus, it has to be decided how to continue with `Serialize`/`Deserialize` for types in `imap-codec`. If the types shall not implement these in the long run, they should be removed for `Fragment` before the 2.0 release as this would be a breaking change.

**Comment by HenningHolmDE** [comment]
@duesee Now do you want to continue on this path?

I started preparing #562, in case we do not want serialization for now.

**Comment by duesee** [comment]
Let's continue with #562  :+1:
